import { ArrowRight, Bot, BrainCircuit, CloudCog, Code2, Cpu, Network, RadioTower, Settings2 } from 'lucide-react';
export const consultServices=[
 {icon:<Code2 className="w-6 h-6"/>,title:'Software Development',text:'Web applications, mobile products, SaaS platforms, APIs and business automation.',href:'/consult/services/web-mobile'},
 {icon:<BrainCircuit className="w-6 h-6"/>,title:'AI & Machine Learning',text:'Predictive systems, computer vision, NLP, intelligent automation and model deployment.',href:'/consult/services/ai-ml'},
 {icon:<CloudCog className="w-6 h-6"/>,title:'Cloud & DevOps',text:'Cloud architecture, deployments, CI/CD, containers, monitoring and infrastructure support.',href:'/consult/services/cloud-devops'},
 {icon:<Cpu className="w-6 h-6"/>,title:'Computer Engineering',text:'Control, robotics, embedded systems, instrumentation, networking and IoT solutions.',href:'/consult/services/engineering'},
];
export const engineering=[{icon:<Settings2/>,title:'Control Engineering'},{icon:<Bot/>,title:'Robotics & Automation'},{icon:<Cpu/>,title:'Embedded & IoT'},{icon:<Network/>,title:'Networking'},{icon:<RadioTower/>,title:'Instrumentation'}];
export function SectionTitle({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <div className="max-w-2xl mb-10"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-600">{eyebrow}</p><h2 className="text-3xl font-extrabold text-navy-900 mt-2">{title}</h2>{text&&<p className="text-muted mt-3 leading-relaxed">{text}</p>}</div>}
export function ServiceCard({item}:{item:typeof consultServices[number]}){return <a href={item.href} className="group rounded-2xl border border-border bg-white p-6 shadow-card hover:shadow-float hover:-translate-y-1 transition-all"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-orange-500 to-pink-600 text-white grid place-items-center">{item.icon}</div><h3 className="font-bold text-lg mt-5">{item.title}</h3><p className="text-sm text-muted mt-2 leading-relaxed">{item.text}</p><span className="inline-flex items-center gap-2 text-sm font-bold text-orange-600 mt-5">Explore service <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform"/></span></a>}
