import {useCallback,useEffect,useState} from 'react';import {Link} from 'react-router-dom';import {PageShell} from '@/components/PageShell';import {Card} from '@/components/ui/Card';import {Button} from '@/components/ui/Button';import {useAuth} from '@/context/AuthContext';import {supabase} from '@/lib/supabase';import {RefreshCw} from 'lucide-react';type Row=Record<string,any>;
export function ConsultOperations(){const {user}=useAuth();const [projects,setProjects]=useState<Row[]>([]),[selected,setSelected]=useState(''),[data,setData]=useState<Record<string,Row[]>>({}),[error,setError]=useState(''),[change,setChange]=useState({title:'',description:''});
const load=useCallback(async()=>{if(!supabase||!user)return;const pr=await supabase.from('consult_projects').select('*').eq('user_id',user.id).order('created_at',{ascending:false});if(pr.error){setError(pr.error.message);return}const ps=pr.data||[];setProjects(ps);const pid=selected||ps[0]?.id||'';if(pid&&!selected)setSelected(pid);if(!pid)return;const client=supabase;const names=['consult_quotations','consult_contracts','consult_milestones','consult_deliverables','consult_invoices','consult_payments','consult_messages','consult_team_members','consult_change_requests'];const rs=await Promise.all(names.map(n=>client.from(n).select('*').eq('project_id',pid).order('created_at',{ascending:false})));const d:Record<string,Row[]>={};names.forEach((n,i)=>d[n]=rs[i].data||[]);const nr=await client.from('consult_notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(20);d.consult_notifications=nr.data||[];setData(d)},[user,selected]);useEffect(()=>{void load()},[load]);
async function submitChange(){if(!supabase||!user||!selected||!change.title.trim()||!change.description.trim())return;const {error:e}=await supabase.from('consult_change_requests').insert({project_id:selected,user_id:user.id,title:change.title.trim(),description:change.description.trim()});if(e){setError(e.message);return}setChange({title:'',description:''});void load()}const money=(n:any)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(n||0));
const section=(title:string,key:string,render:(x:Row)=>React.ReactNode)=><Card><h2 className="font-bold">{title}</h2><div className="mt-4 space-y-3">{(data[key]||[]).map(render)}{!(data[key]||[]).length&&<p className="text-sm text-muted">Nothing recorded yet.</p>}</div></Card>;
return <PageShell product="consult" showAnnouncement={false}><main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-bold text-orange-600">Client workspace</p><h1 className="text-3xl font-black">Consult Business Operations</h1><p className="mt-1 text-muted">Proposals, contracts, milestones, deliverables, invoices, team, messages and scope changes.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>void load()} leftIcon={<RefreshCw className="h-4 w-4"/>}>Refresh</Button><Link to="/consult/portal"><Button>Portal overview</Button></Link></div></div>{error&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<Card className="mt-6"><label className="text-sm font-bold">Project <select className="ml-3 rounded-lg border p-2" value={selected} onChange={e=>setSelected(e.target.value)}>{projects.map(x=><option value={x.id} key={x.id}>{x.project_number} — {x.name}</option>)}</select></label></Card><div className="mt-6 grid gap-5 lg:grid-cols-2">
{section('Proposals & quotations','consult_quotations',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.quote_number}</b><span className="float-right text-xs capitalize">{x.status}</span><p className="text-sm">{money(x.amount)}</p><p className="text-xs text-muted">{x.scope_summary}</p></div>)}
{section('Contracts & agreements','consult_contracts',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.title}</b><span className="float-right text-xs capitalize">{x.status}</span><p className="text-xs text-muted">{x.contract_number} · {String(x.contract_type||'').replaceAll('_',' ')}</p></div>)}
{section('Milestones','consult_milestones',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.title}</b><span className="float-right text-xs capitalize">{x.status}</span><p className="text-xs text-muted">{x.due_at?'Due '+x.due_at:'No due date set'}</p></div>)}
{section('Deliverables','consult_deliverables',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.title}</b><span className="float-right text-xs capitalize">{String(x.status).replaceAll('_',' ')}</span><p className="text-xs text-muted">{x.description||'Project deliverable'}</p></div>)}
{section('Invoices','consult_invoices',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.invoice_number}</b><span className="float-right text-xs capitalize">{x.status}</span><p className="text-sm">{x.title} · {money(x.amount)}</p></div>)}
{section('Project team','consult_team_members',x=><div key={x.id} className="rounded-xl border p-3"><b>{x.display_name}</b><p className="text-xs text-muted">{x.role_title}</p></div>)}
{section('Messages','consult_messages',x=><div key={x.id} className="rounded-xl border p-3 text-sm">{x.body}</div>)}
{section('Notifications','consult_notifications',x=><div key={x.id} className="rounded-xl border p-3"><b className="text-sm">{x.title}</b><p className="text-xs text-muted">{x.body}</p></div>)}
</div><Card className="mt-6"><h2 className="font-bold">Project change request</h2><p className="mt-1 text-sm text-muted">Request additions or scope changes for cost and schedule review before approval.</p><div className="mt-4 grid gap-3"><input className="rounded-lg border p-3 text-sm" placeholder="Change title" value={change.title} onChange={e=>setChange({...change,title:e.target.value})}/><textarea className="rounded-lg border p-3 text-sm" rows={4} placeholder="Describe the requested change" value={change.description} onChange={e=>setChange({...change,description:e.target.value})}/><div><Button disabled={!selected||!change.title.trim()||!change.description.trim()} onClick={()=>void submitChange()}>Submit change request</Button></div></div><div className="mt-5 space-y-2">{(data.consult_change_requests||[]).map(x=><div key={x.id} className="rounded-lg bg-slate-50 p-3 text-sm"><b>{x.title}</b><span className="float-right capitalize">{x.status}</span><p className="mt-1 text-muted">{x.description}</p></div>)}</div></Card></main></PageShell>}